name: Build and Test

# 当 push 到 master 或者打开 Pull Request 时触发工作流
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check runner OS
        run: echo "Runner OS is ${{ runner.os }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Wayland dependency
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install -y libwayland-bin

        # Windows 环境下运行 BAT 脚本
      - name: Run install script on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: install.cmake.bat

      - name: Run install script on Unix (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./install.cmake.sh
          ./install.cmake.sh


